/*
SQLyog Community
MySQL - 5.7.26-log : Database - ppa
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `brands` */

insert  into `brands`(`id`,`code`,`name`,`description`,`created_at`,`updated_at`) values 
(2,'ADM','ADM',NULL,NULL,NULL),
(3,'AHM','AHM',NULL,NULL,NULL),
(4,'CHEMCO','CHEMCO',NULL,NULL,NULL),
(5,'DENSO','DENSO',NULL,NULL,NULL),
(6,'HINO','HINO',NULL,NULL,NULL),
(7,'HITACHI','Hitachi',NULL,NULL,NULL),
(8,'HONDA','Honda',NULL,NULL,NULL),
(9,'HPM','HPM',NULL,NULL,NULL),
(10,'IAMI','IAMI',NULL,NULL,NULL),
(11,'KAWASAKI','KAWASAKI',NULL,NULL,NULL),
(12,'KMI','KMI',NULL,NULL,NULL),
(13,'MARKET','MARKET',NULL,NULL,NULL),
(14,'MITSUBISHI','MITSUBISHI',NULL,NULL,NULL),
(15,'NISAN','NISAN',NULL,NULL,NULL),
(16,'PANASONIC','PANASONIC',NULL,NULL,NULL),
(17,'SIM','SIM',NULL,NULL,NULL),
(18,'SINAR JAYA','SINAR JAYA',NULL,NULL,NULL),
(19,'SUZUKI','SUZUKI',NULL,NULL,NULL),
(20,'TMMIN','TMMIN',NULL,NULL,NULL),
(21,'TOYOTA','TOYOTA',NULL,NULL,NULL),
(22,'TVS','TVS',NULL,NULL,NULL),
(23,'VOLVO','VOLVO',NULL,NULL,NULL),
(24,'YIMM','YIMM',NULL,NULL,NULL),
(25,'YMMA','YMMA',NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
