/*
SQLyog Community
MySQL - 5.7.26-log : Database - ppa
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Data for the table `departments` */

insert  into `departments`(`id`,`name`,`description`,`created_at`,`updated_at`) values 
(1,'DIREKSI',NULL,NULL,NULL),
(2,'FA',NULL,NULL,NULL),
(3,'HRD',NULL,NULL,NULL),
(4,'MARKETING',NULL,NULL,NULL),
(5,'MTC',NULL,NULL,NULL),
(6,'PRS',NULL,NULL,NULL),
(7,'SUPPORT',NULL,NULL,NULL),
(8,'LAB',NULL,NULL,NULL),
(9,'PRODUKSI',NULL,NULL,NULL),
(10,'PRODUKSI COATING',NULL,NULL,NULL),
(11,'PRODUKSI PLATING',NULL,NULL,NULL),
(12,'PRODUKSI TREATMENT/DIPPING',NULL,NULL,NULL),
(13,'QC',NULL,NULL,NULL),
(14,'QCA',NULL,NULL,NULL),
(15,'WWT',NULL,NULL,NULL);

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
